application: rebecca-und-ruben
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.+)
  static_files: \1
  upload: (.*)

- url: /
  static_files: index.html
  upload: index.html
