#application: rebecca-und-ruben
#version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.+)
  static_files: \1
  upload: (.*)

- url: /
  static_files: index.html
  upload: index.html

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.md
- Gruntfile.js
- .gitignore
- package.json
- README.md
- ^node_modules/(.*/)?
- ^.git/(.*/)?
- ^.idea/(.*/)?
